import { Router } from 'express';
import auths from './auths.js';
import analytics from './analytics.js';
import assistants from './assistants.js';
import chapters from './chapters.js';
import courses from './courses.js';
import fields from './fields.js';
import payments from './payments.js';
import subscriptions from './subscriptions.js';
import topics from './topics.js';
import users from './users.js';
import amounts from './amounts.js';
import feedbacks from './feedbacks.js';
import certifications from './certifications.js';
import uploads from './uploads.js';
const routes = Router();

routes.use('/auths', auths);
routes.use('/fields', fields);
routes.use('/assistants', assistants);
routes.use('/courses', courses);
routes.use('/chapters', chapters);
routes.use('/topics', topics);
routes.use('/subscriptions', subscriptions);
routes.use('/payments', payments);
routes.use('/users', users);
routes.use('/amounts', amounts);
routes.use('/feedbacks', feedbacks);
routes.use('/certifications', certifications);
routes.use('/analytics', analytics);
routes.use('/uploads', uploads);

export default routes;